//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond
    {
        public int BondId { get; set; }
        public string Title { get; set; }
        public double Cost { get; set; }
        public string Broker { get; set; }
        public Nullable<double> Coupon { get; set; }
        public Nullable<double> Percent { get; set; }
        public Nullable<int> Nominal { get; set; }
        public System.DateTime Date_of_buy { get; set; }
        public System.DateTime Date_of_maturity { get; set; }
        public int Count { get; set; }
    }
}
